version: '3.7'

services:
 db:
  restart: always
  image: postgres:latest
  container_name: natura-postgres-compose
  environment:
   POSTGRES_USER: ${DB_USERNAME}
   POSTGRES_PASSWORD: ${DB_PASSWORD}
   POSTGRES_DB: ${DB_NAME}
  ports:
   - ${DB_PORT}:${DB_PORT}
  volumes:
   - ./data:/var/lib/postgresql/data
 app:
  restart: always
  container_name: natura-backend-compose

  volumes:
   - ./data:/images
  build:
   context: ./backend
   dockerfile: Dockerfile
  depends_on:
   - db
  env_file:
   - .env
  environment:
   - DB_HOST=db
  ports:
   - '${PORT}:${PORT}'

 web:
  restart: always
  container_name: natura-frontend-compose
  build:
   context: ./frontend
   dockerfile: Dockerfile
  depends_on:
   - app
   - db
  env_file:
   - .env
  ports:
   - 5177:5177
  environment:
   - REACT_APP_API_URL=http://app:${PORT}
