version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: natura-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    restart: always
    container_name: natura_backend
    volumes:
      - ./data:/images
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - '${PORT}:${PORT}'
